language: generic

sudo: false

matrix:
  include:
    - os: linux
      env: ARCH="i686"
      addons:
        apt:
          packages:
            - sbcl
            - texinfo
            - autoconf
            - automake
    - os: linux
      env: ARCH="x86_64"
      addons:
        apt:
          packages:
            - sbcl
            - texinfo
            - autoconf
            - automake
    - os: osx
      env: ARCH="x86_64"
      osx_image: xcode8
      addons:
        homebrew:
            update: true
            packages:
              - sbcl
              - texinfo
              - automake
              - autoconf

before_install:
  - cat doc-Makefile-am.patch | patch -p0 doc/Makefile.am 
  - ./bootstrap
  - ./configure --enable-sbcl --prefix=`pwd`/usr --enable-quiet-build
    
script:
  # compile / install Maxima
  - travis_wait 10 make > build.log
  # run tests
  - (travis_wait 15 make check) || echo "Tests failed."
  # Install (in particular, build docs)
  - make install
