(L : [exp(-a/p),v,1/gamma(v+1)],0);
0$

is(equal(sort(L) , sort(reverse(L))));
true$

(declare(z,complex),domain : complex,0);
0$

/* #4383 great not transitive (so simplifya not idempotent) */
exp(z) + sqrt(exp(z)) + exp(z);
2*exp(z) + sqrt(exp(z))$

is(orderlessp(exp(z),sqrt(exp(z))) # orderlessp(sqrt(exp(z)),exp(z)));
true$

is((a^(b*d))^f(c)/(b*f(c)) = expand((a^(b*d))^f(c)/(b*f(c)),0,0));
true$

(bad: '[
[f(b),a^(b*c),b],
[a^(b*c),b,f(b)], 
[b,f(b),a^(b*c)]
],0);
0$

block([ok : true],
  for i in bad do (
     ok : ok and sort(i) = sort(reverse(i))),
  ok);
true$

/* #365 orderlessp not transitive */

(l: [z+x*(x+2)+v+1,z+x^2+x+v+1,z+(x+1)^2+v],0);
0$

orderlessp(l[1],l[2]);
true$

orderlessp(l[2],l[3]);
true$

orderlessp(l[1],l[3]);
true$

(remvalue(l),0);
0$

(LL : sort([-(1/c^%pi),-(1/(1/c)^%pi),b*c]),0);
0$

orderlessp(first(LL), second(LL));
true$

orderlessp(second(LL), third(LL));
true$

orderlessp(first(LL), third(LL));
true$

(remvalue(LL),0);
0$

/* #3072 orderlessp/great not transitive (2) */

cardinality(map('sort, permutations([A(w*(x-1)), x, A(x-1)])));
1$

/* #4484 more 'great' bugs */

block([domain : 'complex], cardinality(map(sort, permutations([a[1],a,exp(a[1])]))));
1$

block([domain : 'real], cardinality(map(sort, permutations([%e^(a . b),a^^7,a*b]))));
1$

(L : [%e^(a . b),a^^7,a*b],0);
0$

block([ans1,ans2,ans3], 
  ans1 : xreduce("+",L), 
  ans2 : expand(ans1,0,0), 
  ans3 : expand(ans2,0,0),
  [ans1,ans2,ans3]);
[a*b+a^^7+%e^(a . b),a*b+a^^7+%e^(a . b),a*b+a^^7+%e^(a . b)]$

/* Did we make a mess? Let's clean it up!*/
(remvalue(L),remvalue(bad),remove(z,complex), reset(domain), 0);
0$

values;
[]$

facts();
[]$

contexts;
[initial, global]$