@menu
* Introduction to interpol::
* Functions and Variables for interpol::
@end menu

@node Introduction to interpol, Functions and Variables for interpol, Package interpol, Package interpol
@section Introduction to interpol

Package @code{interpol} defines the Lagrangian, the linear and the cubic 
splines methods for polynomial interpolation.

For comments, bugs or suggestions, please contact me at @var{'mario AT edu DOT xunta DOT es'}.

@opencatbox{Categories:}
@category{Numerical methods}
@category{Share packages}
@category{Package interpol}
@closecatbox

@node Functions and Variables for interpol,  , Introduction to interpol, Package interpol
@section Functions and Variables for interpol


@anchor{lagrange}
@deffn {Function} lagrange @
@fname{lagrange} (@var{points}) @
@fname{lagrange} (@var{points}, @var{option})

Computes the polynomial interpolation by the Lagrangian method. Argument @var{points} must be either:

@itemize @bullet
@item
a two column matrix, @code{p:matrix([2,4],[5,6],[9,3])},
@item
a list of pairs, @code{p: [[2,4],[5,6],[9,3]]},
@item
a list of numbers, @code{p: [4,6,3]}, in which case the abscissas will be assigned automatically to 1, 2, 3, etc.
@end itemize

In the first two cases the pairs are ordered with respect to the first coordinate before making computations.

With the @var{option} argument it is possible to select the name for the independent variable, which is @code{'x} by default; to define another one, write something like @code{varname='z}. 

Note that when working with high degree polynomials, floating point evaluations are unstable.

See also @mrefcomma{linearinterpol}  @mrefcomma{cspline}  and @mrefdot{ratinterpol}

Examples:

@c ===beg===
@c load("interpol")$
@c p:[[7,2],[8,2],[1,5],[3,2],[6,7]]$
@c lagrange(p);
@c define(f(x),%)$
@c expand(map(f,[2.3,5/7,%pi]));
@c plot2d ([f,[discrete,p]], [x,0,10], [style,lines,points],
@c        [legend,"Polynomial","Points"])$
@c lagrange(p, varname=w);
@c ===end===
@example maxima
(%i1) load("interpol")$
(%i2) p:[[7,2],[8,2],[1,5],[3,2],[6,7]]$
@group
(%i3) lagrange(p);
      (x - 7) (x - 6) (x - 3) (x - 1)
(%o3) -------------------------------
                    35
   (x - 8) (x - 6) (x - 3) (x - 1)
 - -------------------------------
                 12
   7 (x - 8) (x - 7) (x - 3) (x - 1)
 + ---------------------------------
                  30
   (x - 8) (x - 7) (x - 6) (x - 1)
 - -------------------------------
                 60
   (x - 8) (x - 7) (x - 6) (x - 3)
 + -------------------------------
                 84
@end group
(%i4) define(f(x),%)$
@group
(%i5) expand(map(f,[2.3,5/7,%pi]));
                                 4          3           2
                   919062  73 %pi    701 %pi    8957 %pi
(%o5) [- 1.567535, ------, ------- - -------- + ---------
                   84035     420       210         420
                                                  5288 %pi   186
                                                - -------- + ---]
                                                    105       5
@end group
@group
(%i6) plot2d ([f,[discrete,p]], [x,0,10], [style,lines,points],
       [legend,"Polynomial","Points"])$
@end group
@group
(%i7) lagrange(p, varname=w);
      (w - 7) (w - 6) (w - 3) (w - 1)
(%o7) -------------------------------
                    35
   (w - 8) (w - 6) (w - 3) (w - 1)
 - -------------------------------
                 12
   7 (w - 8) (w - 7) (w - 3) (w - 1)
 + ---------------------------------
                  30
   (w - 8) (w - 7) (w - 6) (w - 1)
 - -------------------------------
                 60
   (w - 8) (w - 7) (w - 6) (w - 3)
 + -------------------------------
                 84
@end group
@end example

@altfigure{interpol1,Example of Lagrange interpolation}

@opencatbox{Categories:}
@category{Package interpol}
@closecatbox

@end deffn


@anchor{charfun2}
@deffn {Function} charfun2 (@var{x}, @var{a}, @var{b})

The characteristic or indicator function on the half-open interval @math{[@var{a}, @var{b})},
that is, including @var{a} and excluding @var{b}.

Package @code{interpol} loads this function.

See also @mrefdot{charfun}

Examples:

When @math{@var{x} >= @var{a}} and @math{@var{x} < @var{b}} evaluates to @code{true} or @code{false},
@code{charfun2} returns 1 or 0, respectively.

@c ===beg===
@c load ("interpol") $
@c charfun2 (5, 0, 100);
@c charfun2 (-5, 0, 100);
@c ===end===
@example maxima
(%i1) load ("interpol") $
@group
(%i2) charfun2 (5, 0, 100);
(%o2)                           1
@end group
@group
(%i3) charfun2 (-5, 0, 100);
(%o3)                           0
@end group
@end example

Otherwise, @code{charfun2} returns a partially-evaluated result in terms of @mref{charfun}.

@c ===beg===
@c load ("interpol") $
@c charfun2 (t, 0, 100);
@c charfun2 (5, u, v);
@c assume (v > u, u > 5);
@c charfun2 (5, u, v);
@c ===end===
@example maxima
(%i1) load ("interpol") $
@group
(%i2) charfun2 (t, 0, 100);
(%o2)            charfun((0 <= t) and (t < 100))
@end group
@group
(%i3) charfun2 (5, u, v);
(%o3)             charfun((u <= 5) and (5 < v))
@end group
@group
(%i4) assume (v > u, u > 5);
(%o4)                    [v > u, u > 5]
@end group
@group
(%i5) charfun2 (5, u, v);
(%o5)                           0
@end group
@end example

@opencatbox{Categories:}
@category{Package interpol}
@closecatbox

@end deffn

@anchor{linearinterpol}
@deffn {Function} linearinterpol @
@fname{linearinterpol} (@var{points}) @
@fname{linearinterpol} (@var{points}, @var{option})

Computes the polynomial interpolation by the linear method. Argument @var{points} must be either:

@itemize @bullet
@item
a two column matrix, @code{p:matrix([2,4],[5,6],[9,3])},
@item
a list of pairs, @code{p: [[2,4],[5,6],[9,3]]},
@item
a list of numbers, @code{p: [4,6,3]}, in which case the abscissas will be assigned automatically to 1, 2, 3, etc.
@end itemize

In the first two cases the pairs are ordered with respect to the first coordinate before making computations.

With the @var{option} argument it is possible to select the name for the independent variable, which is @code{'x} by default; to define another one, write something like @code{varname='z}. 

See also @mrefcomma{lagrange}  @mrefcomma{cspline}  and @mrefdot{ratinterpol}

Examples:

@c ===beg===
@c load ("interpol") $
@c p: matrix([7,2],[8,3],[1,5],[3,2],[6,7])$
@c linearinterpol(p);
@c define(f(x),%)$
@c map(f, [7.3,25/7,%pi]);
@c float(%);
@c plot2d ([f,[discrete,args(p)]], [x,-5,20], [style,lines,points],
@c     [legend,"Interpolation line","Points"])$
@c lagrange(p, varname=w);
@c ===end===
@example maxima
(%i1) load ("interpol") $
(%i2) p: matrix([7,2],[8,3],[1,5],[3,2],[6,7])$
@group
(%i3) linearinterpol(p);
       13   3 x
(%o3) (-- - ---) charfun(x < 3) + charfun((3 <= x) and (x < 6))
       2     2
  5 x
 (--- - 3) + charfun(7 <= x) (x - 5)
   3
 + charfun((6 <= x) and (x < 7)) (37 - 5 x)
@end group
(%i4) define(f(x),%)$
@group
(%i5) map(f, [7.3,25/7,%pi]);
                            62  5 %pi
(%o5)                 [2.3, --, ----- - 3]
                            21    3
@end group
@group
(%i6) float(%);
(%o6)     [2.3, 2.9523809523809526, 2.235987755982989]
@end group
@group
(%i7) plot2d ([f,[discrete,args(p)]], [x,-5,20], [style,lines,points],
    [legend,"Interpolation line","Points"])$
@end group
@group
(%i8) lagrange(p, varname=w);
      3 (w - 7) (w - 6) (w - 3) (w - 1)
(%o8) ---------------------------------
                     70
   (w - 8) (w - 6) (w - 3) (w - 1)
 - -------------------------------
                 12
   7 (w - 8) (w - 7) (w - 3) (w - 1)
 + ---------------------------------
                  30
   (w - 8) (w - 7) (w - 6) (w - 1)
 - -------------------------------
                 60
   (w - 8) (w - 7) (w - 6) (w - 3)
 + -------------------------------
                 84
@end group
@end example

@altfigure{interpol2,Example of linear interpolation}

@opencatbox{Categories:}
@category{Package interpol}
@closecatbox

@end deffn

@anchor{cspline}
@deffn {Function} cspline @
@fname{cspline} (@var{points}) @
@fname{cspline} (@var{points}, @var{option1}, @var{option2}, ...)

Computes the polynomial interpolation by the cubic splines method. Argument @var{points} must be either:

@itemize @bullet
@item
a two column matrix, @code{p:matrix([2,4],[5,6],[9,3])},
@item
a list of pairs, @code{p: [[2,4],[5,6],[9,3]]},
@item
a list of numbers, @code{p: [4,6,3]}, in which case the abscissas will be assigned automatically to 1, 2, 3, etc.
@end itemize

In the first two cases the pairs are ordered with respect to the first coordinate before making computations.

There are three options to fit specific needs:
@itemize @bullet
@item
@code{'d1}, default @code{'unknown}, is the first derivative at @math{x_1}; if it is @code{'unknown}, the second derivative at @math{x_1} is made equal to 0 (natural cubic spline); if it is equal to a number, the second derivative is calculated based on this number.

@item
@code{'dn}, default @code{'unknown}, is the first derivative at @math{x_n}; if it is @code{'unknown}, the second derivative at @math{x_n} is made equal to 0 (natural cubic spline); if it is equal to a number, the second derivative is calculated based on this number.

@item
@code{'varname}, default @code{'x}, is the name of the independent variable.
@end itemize

See also @mrefcomma{lagrange}  @mrefcomma{linearinterpol}  and @mrefdot{ratinterpol}

Examples:
@c ===beg===
@c load("interpol")$
@c p:[[7,2],[8,2],[1,5],[3,2],[6,7]]$
@c cspline(p);
@c define (f(x),%)$
@c float (map (f, [2.3,5/7,%pi]));
@c plot2d ([f,[discrete,p]], [x,0,10], [y,-8,13], [style,lines,points],
@c     [legend,"Cubic splines","Points"])$
@c cspline(p,d1=0,dn=0);
@c define (g(x),%)$
@c plot2d ([f,g,[discrete,p]], [x,0,10], [y,-15,15], [style,lines,lines,points],
@c        [legend,"Cubic splines","Splines with derivatives","Points"])$
@c ===end===
@example maxima
(%i1) load("interpol")$
(%i2) p:[[7,2],[8,2],[1,5],[3,2],[6,7]]$
@group
(%i3) cspline(p);
             3         2
       1159 x    1159 x    6091 x   8283
(%o3) (------- - ------- - ------ + ----) charfun(x < 3)
        3288      1096      3288    1096
 + charfun((6 <= x) and (x < 7))
        3          2
  4715 x    15209 x    579277 x   199575
 (------- - -------- + -------- - ------)
   1644       274        1644      274
 + charfun((3 <= x) and (x < 6))
          3         2
    3287 x    2223 x    48275 x   9609
 (- ------- + ------- - ------- + ----)
     4932       274      1644     274
                            3         2
                      2587 x    5174 x    494117 x   108928
 + charfun(7 <= x) (- ------- + ------- - -------- + ------)
                       1644       137       1644      137
@end group
(%i4) define (f(x),%)$
@group
(%i5) float (map (f, [2.3,5/7,%pi]));
(%o5) [1.9914607664233568, 5.823200187269903, 2.2274053124295072]
@end group
@group
(%i6) plot2d ([f,[discrete,p]], [x,0,10], [y,-8,13], [style,lines,points],
    [legend,"Cubic splines","Points"])$
@end group
@group
(%i7) cspline(p,d1=0,dn=0);
             3          2
       1949 x    11437 x    17027 x   1247
(%o7) (------- - -------- + ------- + ----) charfun(x < 3)
        2256       2256      2256     752
 + charfun((6 <= x) and (x < 7))
       3          2
  607 x    35147 x    55706 x   38420
 (------ - -------- + ------- - -----)
   188       564        141      47
 + charfun((3 <= x) and (x < 6))
          3         2
    3895 x    1807 x    5146 x   2148
 (- ------- + ------- - ------ + ----)
     5076       188      141      47
                            3          2
                      1547 x    35581 x    68068 x   173546
 + charfun(7 <= x) (- ------- + -------- - ------- + ------)
                        564       564        141      141
@end group
(%i8) define (g(x),%)$
@group
(%i9) plot2d ([f,g,[discrete,p]], [x,0,10], [y,-15,15], [style,lines,lines,points],
       [legend,"Cubic splines","Splines with derivatives","Points"])$
@end group
@end example

@altfigure{interpol3,Example of cubic splines interpolation}

@altfigure{interpol4,Example of cubic splines interpolation with and without derivatives}

@opencatbox{Categories:}
@category{Package interpol}
@closecatbox

@end deffn

@anchor{ratinterpol}
@deffn {Function} ratinterpol @
@fname{ratinterpol} (@var{points}, @var{numdeg}) @
@fname{ratinterpol} (@var{points}, @var{numdeg}, @var{option1})

Generates a rational interpolator for data given by @var{points} and the degree of the numerator
being equal to @var{numdeg}; the degree of the denominator is calculated
automatically. Argument @var{points} must be either:

@itemize @bullet
@item
a two column matrix, @code{p:matrix([2,4],[5,6],[9,3])},
@item
a list of pairs, @code{p: [[2,4],[5,6],[9,3]]},
@item
a list of numbers, @code{p: [4,6,3]}, in which case the abscissas will be assigned automatically to 1, 2, 3, etc.
@end itemize

In the first two cases the pairs are ordered with respect to the first coordinate before making computations.

There is one option to fit specific needs:
@itemize @bullet
@item
@code{'varname}, default @code{'x}, is the name of the independent variable.
@end itemize

See also @mrefcomma{lagrange}  @mrefcomma{linearinterpol}  @mrefcomma{cspline}  @mrefcomma{minpack_lsquares}  and @ref{Package lbfgs}

Examples:

@c ===beg===
@c load("interpol")$
@c p:[[7.2,2.5],[8.5,2.1],[1.6,5.1],[3.4,2.4],[6.7,7.9]]$
@c for k:0 thru length(p)-1 do
@c plot2d([ratinterpol(p,k),[discrete,p]], [x,0,9], [y,0,10], [style,lines,points],
@c   [title,concat("Degree of numerator = ",k)], nolegend, gnuplot)$
@c ===end===
@example maxima
(%i1) load("interpol")$
(%i2) p:[[7.2,2.5],[8.5,2.1],[1.6,5.1],[3.4,2.4],[6.7,7.9]]$
@group
(%i3) for k:0 thru length(p)-1 do
@end group
@group
(%i4) plot2d([ratinterpol(p,k),[discrete,p]], [x,0,9], [y,0,10], [style,lines,points],
  [title,concat("Degree of numerator = ",k)], nolegend, gnuplot)$
@end group
@end example

@altfigure{interpol5,Example of rational interpolation of degree 0}

@altfigure{interpol6,Example of rational interpolation of degree 1}

@altfigure{interpol7,Example of rational interpolation of degree 2}

@altfigure{interpol8,Example of rational interpolation of degree 3}

@altfigure{interpol9,Example of rational interpolation of degree 4}

@opencatbox{Categories:}
@category{Package interpol}
@closecatbox

@end deffn
